defaults:
  # - visualization_config # uncomment to use visualization_config.yaml file to set up model_prediction
  - generation_config
  - _self_

hydra:
  searchpath:
    - file://nemo_skills/inference