defaults:
  # add custom config to set up model_prediction
  - model_predictions
  - generation_config
  - base_visualization_config
  - _self_

hydra:
  searchpath:
    - file://nemo_skills/inference
