# Generic prompt for Nemotron-base fewshot

few_shot_examples:
  template: "Example question:\n{question}{context}\n\nExample solution:\n{generation}\n\n\n\n\n\n"

system: ""

user: |-
  Here are some examples of questions and solutions followed by a new question that you need to solve.
  Make sure to put the answer (and only answer) inside \boxed{{}}.

  {examples}Question:
  {question}{context}

  Don't forget that your final answer should be inside \boxed{{}}!

prompt_template: |-
  <extra_id_0>System
  {system}
  <extra_id_1>User
  {user}
  <extra_id_1>Assistant
  {generation}

stop_phrases: ["\n\n\n\n\n\n", "<extra_id_1>"]

