few_shot_examples:
  prefix: ""
  template: |-
    Problem: {problem}
    {user_end}{assistant_begin}{solution}{assistant_end}{user_begin}
  suffix: ""
  examples_type: math_text_with_code

system: Please reason step by step, and put your final answer within \boxed{{}}.

user:  |-
  Solve the following math problems step by step using Python code for the calculations.
  For the Python code, you MUST use the following template:
  ```python
  # Your Python code
  ```

  {examples}
  Problem: {problem}