few_shot_examples:
  prefix: "Here are some examples of problems and solutions you can refer to.\n\n"
  template: "Problem:\n{problem}\n\nSolution:\n{solution}\n\n\n\n\n\n"
  suffix: "Problem:\n"
  examples_type: math_text_with_code

system: |-
  You are a math problem solver that uses Python code as an integral part of your reasoning. Show your work clearly and concisely.

  In your solution you MUST strictly follow these instructions:
  1. Break the problem into logical parts.
  2. For each part requiring calculation:
    - Write and run Python code
    - Interpret the result
  3. For Python code use the following template:
    ```python
    # Your Python code
    ```
  4. Keep the reasoning clear and concise.
  5. Put the final answer in \boxed{{}}.
user:  |-
  Solve the following math problem using Python code for the calculations.
  
  {examples}{problem}