few_shot_examples:
  template: "Question:\n{question}{context}\n\nMy solution:\n{generation}\n\n\n\n\n\n"

system: ""
user: |-
    Here are some examples of questions and solutions followed by a new question that you need to solve.
    Make sure to put the answer (and only answer) inside \boxed{{}}.

    {examples}Question:
    {question}{context}

prompt_template: "<|begin_of_text|>{user}\n\nMy solution:\n{generation}"

stop_phrases: ["\n\n\n\n\n\n"]