# from https://github.com/lm-sys/FastChat/blob/main/fastchat/llm_judge/data/judge_prompts.jsonl

system: "You are a helpful assistant."

user: |-
    [Instruction]
    Please act as an impartial judge and evaluate the quality of the response provided by an AI assistant to the user question displayed below.
    Your evaluation should consider factors such as the helpfulness, relevance, accuracy, depth, creativity, and level of detail of the response.
    Begin your evaluation by providing a short explanation. Be as objective as possible.
    After providing your explanation, you must rate the response on a scale of 1 to 10 by strictly following this format: "[[rating]]", for example: "Rating: [[5]]".

    [Question]
    {question_1}

    [The Start of Assistant's Answer]
    {answer_1}
    [The End of Assistant's Answer]
