# from https://github.com/lm-sys/FastChat/blob/main/fastchat/llm_judge/data/judge_prompts.jsonl

system: "You are a helpful assistant."

user: |-
    [Instruction]
    Please act as an impartial judge and evaluate the quality of the response provided by an AI assistant to the user question displayed below.
    Your evaluation should consider correctness and helpfulness.
    You will be given a reference answer and the assistant's answer.
    Begin your evaluation by comparing the assistant's answer with the reference answer.
    Identify and correct any mistakes. Be as objective as possible.
    After providing your explanation, you must rate the response on a scale of 1 to 10 by strictly following this format: "[[rating]]", for example: "Rating: [[5]]".

    [Question]
    {question_1}

    [The Start of Reference Answer]
    {ref_answer_1}
    [The End of Reference Answer]

    [The Start of Assistant's Answer]
    {answer_1}
    [The End of Assistant's Answer]
