few_shot_examples:
  prefix: ""
  template: |-
    Solve the following math problem efficiently and clearly.

    Write a detailed step-by-step solution, using Python code for all nontrivial calculations.

    Regardless of the approach, always conclude with:

    Therefore, the final answer is $\boxed{{answer}}$. I hope it is correct.

    Where [answer] is just the final number or expression that solves the problem.
    
    Problem: {problem}{user_end}{assistant_begin}{solution}{assistant_end}{user_begin}
  suffix: ""
  examples_type: math_text_with_code

system: ""

user: |-
  {examples}
  Solve the following math problem efficiently and clearly.

  Write a detailed step-by-step solution, using Python code for all nontrivial calculations.

  Regardless of the approach, always conclude with:

  Therefore, the final answer is $\boxed{{answer}}$. I hope it is correct.

  Where [answer] is just the final number or expression that solves the problem.
  
  Problem: {problem}