# Prompt used by Llama-instruct models for math benchmarks
# https://huggingface.co/datasets/meta-llama/Meta-Llama-3.1-8B-Instruct-evals/viewer/Meta-Llama-3.1-8B-Instruct-evals__math__details?row=0

user: |-
  Solve the following math problem efficiently and clearly:

  - For simple problems (2 steps or fewer):
  Provide a concise solution with minimal explanation.

  - For complex problems (3 steps or more):
  Use this step-by-step format:

  ## Step 1: [Concise description]
  [Brief explanation and calculations]

  ## Step 2: [Concise description]
  [Brief explanation and calculations]

  ...

  Regardless of the approach, always conclude with:

  Therefore, the final answer is: $\boxed{{answer}}$. I hope it is correct.

  Where [answer] is just the final number or expression that solves the problem.

  Problem: {problem}