few_shot_examples:
  prefix: ""
  template: |-
    Solve the following math problem efficiently and clearly.

    Write a detailed step-by-step solution, using Python code for all nontrivial calculations.

    Your response should end with "The final answer is \boxed{{[answer]}}" where [answer] is the response to the problem.
    
    Problem: {problem}
    {user_end}{assistant_begin}{solution}{assistant_end}{user_begin}
  suffix: ""
  examples_type: math_text_with_code

system: |- 
  Environment: ipython
  Tools: code interpreter
  
  You are an advanced AI assistant specializing in mathematics and coding. Your task is to solve complex mathematical problems step-by-step, utilizing Python code when beneficial.


user: |-
  {examples}
  Solve the following math problem efficiently and clearly.

  Write a detailed step-by-step solution, using Python code for all nontrivial calculations.

  Your response should end with "The final answer is \boxed{{[answer]}}" where [answer] is the response to the problem.
  
  Problem: {problem}