# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# copied from https://github.com/NVIDIA/TensorRT-LLM?tab=readme-ov-file#installation

FROM nvidia/cuda:12.1.0-devel-ubuntu22.04

# Install dependencies, TensorRT-LLM requires Python 3.10
RUN apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev

RUN ["ln", "-sf", "/usr/bin/python3", "/usr/bin/python"]
RUN ["ln", "-sf", "/usr/bin/pip3", "/usr/bin/pip"]

# Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
# If you want to install the stable version (corresponding to the release branch), please
# remove the `--pre` option.

# pinning to the tested dev version, until the next release.
RUN pip install tensorrt_llm==0.8.0 -U --pre --extra-index-url https://pypi.nvidia.com

# installing packages required for our server code
RUN pip install flask flask_restful hydra-core tqdm pyyaml numpy backoff

# bug fix https://github.com/NVIDIA/TensorRT-LLM/pull/1146
RUN pip install mpmath==1.3.0
