# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:24.03-py3

# build an image that includes only the nemo dependencies, ensures that dependencies
# are included first for optimal caching, and useful for building a development
# image (by specifying build target as `nemo-deps`)
FROM ${BASE_IMAGE} AS vllm-deps

# install vllm dependencies
WORKDIR /opt

# https://github.com/vllm-project/vllm/pull/8896
# https://github.com/vllm-project/vllm/commit/bc2ef1f77c1578612198f60ec392731efb3847c5
# Bug introduced in future PRs have made us revert to this commit
# See discussion on bug here - https://github.com/vllm-project/vllm/pull/9090
ARG VLLM_HASH=bc2ef1f77c1578612198f60ec392731efb3847c5

RUN git clone https://github.com/vllm-project/vllm.git && \
  cd vllm && \
  git checkout ${VLLM_HASH} && \
  pip install -e . && \
  cd ..

# Install Flash Infer
# ALWAYS UPDATE FROM https://github.com/vllm-project/vllm/blob/main/Dockerfile
ARG FLASHINFER_URL=https://github.com/flashinfer-ai/flashinfer/releases/download/v0.1.6/flashinfer-0.1.6+cu121torch2.4-cp310-cp310-linux_x86_64.whl

RUN pip install $FLASHINFER_URL


# Install requirements
RUN pip install geventhttpclient outlines sentencepiece transformers>=4.45.2 sentence-transformers>=2.2.2 && \
    pip install "megablocks==0.5.1"

WORKDIR /opt

# Set environment variables for mounted HF Cache
RUN [[ -d /cache/huggingface/ ]] || mkdir -p /cache/huggingface/
# Add VLLM to PYTHONPATH
ENV PYTHONPATH=/opt/vllm:$PYTHONPATH
ENV HF_HOME=/cache/huggingface
ENV TRANSFORMERS_CACHE=/cache/huggingface/transformers
ENV HUGGINGFACE_HUB_CACHE=/cache/huggingface/hub
ENV HF_DATASETS_CACHE=/cache/huggingface/datasets

# Expose port for vLLM API
EXPOSE 5000
