# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:23.10-py3

# build an image that includes only the nemo dependencies, ensures that dependencies
# are included first for optimal caching, and useful for building a development
# image (by specifying build target as `nemo-deps`)
FROM ${BASE_IMAGE} as vllm-deps

# Ensure apt-get won't prompt for selecting options
ENV DEBIAN_FRONTEND=noninteractive
# libavdevice-dev rerquired for latest torchaudio
RUN apt-get update && \
  apt-get upgrade -y && \
  rm -rf /var/lib/apt/lists/*

# install vllm dependencies
WORKDIR /workspace/

# Hack to force vllm to build even though logic for the check is flawed in their setup.py
ENV TORCH_CUDA_ARCH_LIST="8.0 8.6 9.0+PTX"

# v0.4.2
ARG VLLM_HASH=c7f2cf2b7f67bce5842fedfdba508440fe257375

RUN git clone https://github.com/vllm-project/vllm.git && \
  cd vllm && \
  git checkout ${VLLM_HASH} && \
  pip3 install -e . && \
  cd ..


# Install requirements
RUN pip install openai>=1.3 ray pydantic flufl.lock fire text_dedup wandb hydra-core geventhttpclient && \
    pip install rouge_score outlines sentencepiece transformers>=4.40 sentence-transformers>=2.2.2

WORKDIR /workspace

# Set environment variables for mounted HF Cache
RUN [[ -d /cache/huggingface/ ]] || mkdir -p /cache/huggingface/
# Add VLLM to PYTHONPATH
ENV PYTHONPATH=/workspace/vllm:$PYTHONPATH
ENV HF_HOME=/cache/huggingface
ENV TRANSFORMERS_CACHE=/cache/huggingface/transformers
ENV HUGGINGFACE_HUB_CACHE=/cache/huggingface/hub
ENV HF_DATASETS_CACHE=/cache/huggingface/datasets

COPY requirements.txt /opt/requirements.txt
RUN pip install -r /opt/requirements.txt

# Expose port for vLLM API
EXPOSE 5000
