processors_to_run: all

processors:
  - _target_: nemo_skills.finetuning.data_preparation_utils.preprocessing.ReadData
    prediction_jsonl_files: /home/dgitman/imoshkov/data/math_text_detailed/output-rs*.jsonl
    # output_manifest_file: /Users/imoshkov/prog/math_reasoning/Nemo-Skills/nemo_skills/finetuning/data_preparation_utils/sdp_configs/test-output.jsonl
    # -> {question, solution, metadata}

  - _target_: nemo_skills.finetuning.data_preparation_utils.filters.DropMultiBoxed
    test_cases:
      - {input: {generation: "He had \\boxed{3} 4090s and \\boxed{2} 4080s"}, output: null}
      - {input: {generation: "She had \\boxed{6} 4090s"}, output: {generation: "She had \\boxed{6} 4090s"}}
      - {input: {generation: "boxed boxed 42"}, output: {generation: "boxed boxed 42"}}

  # - _target_: nemo_skills.finetuning.data_preparation_utils.filters.DropUselessCode

  # - _target_: nemo_skills.finetuning.data_preparation_utils.filters.DropBrokenCode

  - _target_: nemo_skills.finetuning.data_preparation_utils.filters.TrimSolutions
    test_cases:
      - {input: {generation: "Solution ends at \\boxed{0}\nThis line is useless."}, output: {generation: "Solution ends at \\boxed{0}"}}
      - {input: {generation: "Solution continues \\boxed{7} after boxed"}, output: {generation: "Solution continues \\boxed{7} after boxed"}}

  - _target_: nemo_skills.finetuning.data_preparation_utils.filters.SplitArithmetic
    test_cases:
      - {input: {generation: "1 + 2 + 3 + 4 = 10"}, output: {generation: "1 + 2 + 3 + 4 = 3 + 3 + 4 = 6 + 4 = 10"}}
      - {input: {generation: "1 + 7 * 19 = 134"}, output: {generation: "1 + 7 * 19 = 1 + 133 = 134"}}
      - {input: {generation: "3 * (1 + 7) / 4 = 6"}, output: {generation: "3 * (1 + 7) / 4 = 3 * 8 / 4 = 24 / 4 = 6"}}

  # # ...
  - _target_: nemo_skills.finetuning.data_preparation_utils.preprocessing.GroupSamples
    # input_manifest_file: /Users/imoshkov/prog/math_reasoning/Nemo-Skills/nemo_skills/finetuning/data_preparation_utils/sdp_configs/test-output.jsonl
    # output_manifest_file: /Users/imoshkov/prog/math_reasoning/Nemo-Skills/nemo_skills/finetuning/data_preparation_utils/sdp_configs/test-output-grouped.jsonl
  # # -> {question, [solutions, metadata list]}

  - _target_: nemo_skills.finetuning.data_preparation_utils.filters.CodeTextFilter
    # input_manifest_file: /Users/imoshkov/prog/math_reasoning/Nemo-Skills/nemo_skills/finetuning/data_preparation_utils/sdp_configs/test-output-grouped.jsonl
    # output_manifest_file: /Users/imoshkov/prog/math_reasoning/Nemo-Skills/nemo_skills/finetuning/data_preparation_utils/sdp_configs/test-output-filtered.jsonl
    filter_type: null

  - _target_: nemo_skills.finetuning.data_preparation_utils.preprocessing.ShuffleAndDownsampleData
    # input_manifest_file: /Users/imoshkov/prog/math_reasoning/Nemo-Skills/nemo_skills/finetuning/data_preparation_utils/sdp_configs/test-output-filtered.jsonl
    # output_manifest_file: /Users/imoshkov/prog/math_reasoning/Nemo-Skills/nemo_skills/finetuning/data_preparation_utils/sdp_configs/test-output-shuffled.jsonl
    num_samples: null
    sampling_method: random
    random_seed: 42

  - _target_: nemo_skills.finetuning.data_preparation_utils.preprocessing.WriteFinalSftManifest
    # input_manifest_file: /Users/imoshkov/prog/math_reasoning/Nemo-Skills/nemo_skills/finetuning/data_preparation_utils/sdp_configs/test-output-shuffled.jsonl
    output_manifest_file: data_preparation_utils/sdp_configs/test-output-final.jsonl
    prompt_type: openmathinstruct/sft
