name: NeMo Inspector Tool Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  inspector-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements/inspector.txt
        pip install -r requirements/inspector-tests.txt
        pip install -r requirements/common-tests.txt

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@master

    - name: Run NeMo inspector tests
      run: |
        export DISPLAY=:99
        sudo Xvfb :99 -ac &
        python -m pytest nemo_inspector/tests/ --reruns 3 --reruns-delay 1 --junitxml=results.xml --cov-report=term-missing:skip-covered --cov=visualization --durations=30 -vv
