name: Visualization Tool Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r visualization/requirements.txt
        pip install -r visualization/test-requirements.txt
        pip install pytest pytest-cov

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@master

    - name: Run visualization tests
      run: |
        export DISPLAY=:99
        sudo Xvfb :99 -ac &
        python -m pytest visualization/tests/ --reruns 3 --reruns-delay 1 --junitxml=results.xml --cov-report=term-missing:skip-covered --cov=visualization --durations=30 -vv

    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: test-coverage-report
        path: results.xml